# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # MongoDB local server
  config.vm.define "mongo" do |mongo|
  	mongo.vm.hostname="mongo-dev"
    mongo.vm.provider "docker" do |d|
      d.image = "mongo"
      d.ports = ["27017:27017"]
      d.vagrant_vagrantfile = "./Vagrantfile.proxy"
    end
  end

  # Docker Registry
  config.vm.define "registry" do |reg|
    reg.vm.hostname="registry-dev"
    reg.vm.provider "docker" do |d|
      d.image = "registry"
      d.ports = ["5000:5000"]
      d.env = { :SEARCH_BACKEND => "sqlalchemy" }
      d.vagrant_vagrantfile = "./Vagrantfile.proxy"
    end
  end

end  